"""Detection signals for Provenance Guard.

Signal 1 (this module): GROQ semantic classification. Judges the meaning and flow
of logic of the text, never its surface structure, and returns a probability that
the text is AI-generated along with the detected genre and a short rationale.

Signal 2 (stylometric heuristics) arrives in Milestone 4.
"""

import json
import os

from dotenv import load_dotenv
from groq import Groq

load_dotenv()

MODEL = "llama-3.3-70b-versatile"

_client = None


def _get_client():
    global _client
    if _client is None:
        _client = Groq(api_key=os.environ["GROQ_API_KEY"])
    return _client


SYSTEM_PROMPT = """You are a text-provenance analyst. Judge whether a passage was \
written by a human or generated by an AI, based ONLY on semantics: coherence, \
argument progression, factual consistency, topical depth, and how naturally the \
ideas flow. Do NOT judge punctuation, formatting, em dashes, or surface grammar; \
a separate stylometric signal handles those.

First identify the genre (one of: poem, short_story, blog, novel, news, other), \
since "good logical flow" means different things per genre. Then estimate p_ai, \
the probability from 0.0 to 1.0 that the text is AI-generated.

Respond ONLY with a JSON object of exactly this shape:
{"p_ai": <float 0..1>, "genre": "<genre>", "rationale": "<one sentence>"}"""


def groq_signal(text):
    """Return the semantic signal for a piece of text.

    Returns a dict: {"llm_score": float, "genre": str, "rationale": str}.
    llm_score is P(AI) in [0, 1]. On any API/parse failure we return a neutral
    0.5 so the pipeline falls back to uncertain rather than guessing.
    """
    try:
        resp = _get_client().chat.completions.create(
            model=MODEL,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": text},
            ],
            temperature=0,
            response_format={"type": "json_object"},
        )
        data = json.loads(resp.choices[0].message.content)
        score = float(data.get("p_ai", 0.5))
        score = max(0.0, min(1.0, score))
        return {
            "llm_score": score,
            "genre": data.get("genre", "other"),
            "rationale": data.get("rationale", ""),
        }
    except Exception as exc:  # noqa: BLE001 - degrade gracefully to uncertain
        return {
            "llm_score": 0.5,
            "genre": "other",
            "rationale": f"signal unavailable ({type(exc).__name__}), defaulting to uncertain",
        }


if __name__ == "__main__":
    # Quick standalone test: call the signal directly and inspect its output.
    samples = {
        "clearly_ai": (
            "Artificial intelligence represents a transformative paradigm shift in "
            "modern society. It is important to note that while the benefits of AI are "
            "numerous, it is equally essential to consider the ethical implications. "
            "Furthermore, stakeholders across various sectors must collaborate to "
            "ensure responsible deployment."
        ),
        "clearly_human": (
            "ok so i finally tried that new ramen place downtown and honestly? "
            "underwhelming. the broth was fine but they put WAY too much sodium in it "
            "and i was thirsty for like three hours after."
        ),
    }
    for name, sample in samples.items():
        print(name, "->", groq_signal(sample))
