"""Detection signals for Provenance Guard.

Signal 1 (this module): GROQ semantic classification. Judges the meaning and flow
of logic of the text, never its surface structure, and returns a probability that
the text is AI-generated along with the detected genre and a short rationale.

Signal 2 (stylometric heuristics) arrives in Milestone 4.
"""

import json
import os
import re
import statistics
import zlib

from dotenv import load_dotenv
from groq import Groq

load_dotenv()

MODEL = "llama-3.3-70b-versatile"

_client = None


def _get_client():
    global _client
    if _client is None:
        _client = Groq(api_key=os.environ["GROQ_API_KEY"])
    return _client


_SYSTEM_PROMPT_TEXT = """You are a text-provenance analyst. Judge whether a passage was \
written by a human or generated by an AI, based ONLY on semantics: coherence, \
argument progression, factual consistency, topical depth, and how naturally the \
ideas flow. Do NOT judge punctuation, formatting, em dashes, or surface grammar; \
a separate stylometric signal handles those.

First identify the genre (one of: poem, short_story, blog, novel, news, other), \
since "good logical flow" means different things per genre. Then estimate p_ai, \
the probability from 0.0 to 1.0 that the text is AI-generated.

Respond ONLY with a JSON object of exactly this shape:
{"p_ai": <float 0..1>, "genre": "<genre>", "rationale": "<one sentence>"}"""

_SYSTEM_PROMPT_IMAGE = """You are a text-provenance analyst reviewing an image caption \
or alt-text description. Judge whether it was written by a human or generated by an AI, \
based ONLY on semantics: does it have the specific, sometimes imperfect detail of a human \
noticing something, or the fluent but generic completeness of an AI caption? Do NOT judge \
grammar, punctuation, or formatting.

Captions are short by nature, so weight your judgment toward specificity and naturalness \
of observation rather than length or flow. Set genre to "image_description".

Respond ONLY with a JSON object of exactly this shape:
{"p_ai": <float 0..1>, "genre": "image_description", "rationale": "<one sentence>"}"""


def groq_signal(text, content_type="text"):
    """Return the semantic signal for a piece of text.

    Returns a dict: {"llm_score": float, "genre": str, "rationale": str}.
    llm_score is P(AI) in [0, 1]. On any API/parse failure we return a neutral
    0.5 so the pipeline falls back to uncertain rather than guessing.
    content_type: "text" (default) or "image_description" (caption/alt-text).
    """
    system = _SYSTEM_PROMPT_IMAGE if content_type == "image_description" else _SYSTEM_PROMPT_TEXT
    try:
        resp = _get_client().chat.completions.create(
            model=MODEL,
            messages=[
                {"role": "system", "content": system},
                {"role": "user", "content": text},
            ],
            temperature=0,
            response_format={"type": "json_object"},
        )
        data = json.loads(resp.choices[0].message.content)
        score = float(data.get("p_ai", 0.5))
        score = max(0.0, min(1.0, score))
        return {
            "llm_score": score,
            "genre": data.get("genre", "other"),
            "rationale": data.get("rationale", ""),
        }
    except Exception as exc:  # noqa: BLE001 - degrade gracefully to uncertain
        return {
            "llm_score": 0.5,
            "genre": "other",
            "rationale": f"signal unavailable ({type(exc).__name__}), defaulting to uncertain",
        }


# --------------------------------------------------------------------------- #
# Signal 2: stylometric heuristics (pure Python, structure only)
# --------------------------------------------------------------------------- #

# Connective words/phrases that AI text leans on far more than human writing.
_TRANSITIONS = {
    "however", "moreover", "furthermore", "additionally", "therefore",
    "consequently", "nevertheless", "nonetheless", "thus", "hence", "overall",
    "indeed", "notably", "specifically", "ultimately", "essentially",
}
_TRANSITION_PHRASES = [
    "it is important to note", "it's important to note", "plays a crucial role",
    "in conclusion", "on the other hand", "as a result", "in today's world",
    "when it comes to", "a wide range of",
]

# Short text below this word count makes every heuristic unreliable, so we
# abstain to a neutral 0.5 (the pipeline then lands on uncertain).
_MIN_WORDS = 30


def _clamp(x):
    return max(0.0, min(1.0, x))


def _words(text):
    return re.findall(r"[a-z']+", text.lower())


def stylometric_signal(text, genre=None, content_type="text"):
    """Return a structure-only P(AI) for the text.

    Returns {"stylo_score": float, "features": {name: sub_score}}. Each sub-score
    is an AI-likelihood in [0, 1]; the overall stylo_score is their mean. genre is
    accepted for future per-genre calibration; the base thresholds are used for now.
    content_type: "text" (default) or "image_description" -- captions use a lower
    minimum-word threshold since they are short by nature.
    """
    words = _words(text)
    sentences = [s.strip() for s in re.split(r"[.!?\n]+", text) if s.strip()]
    n_words = len(words)

    min_words = 8 if content_type == "image_description" else _MIN_WORDS
    if n_words < min_words:
        return {"stylo_score": 0.5, "features": {"note": "text too short to score"}}

    features = {}

    # 1. Burstiness: humans vary sentence length a lot, AI clusters tightly.
    #    Low coefficient of variation (std/mean) -> AI-like.
    if len(sentences) >= 2:
        lens = [len(_words(s)) for s in sentences]
        mean_len = statistics.mean(lens)
        cv = statistics.pstdev(lens) / mean_len if mean_len else 0.0
        features["burstiness"] = _clamp(1.0 - cv / 0.7)

    # 2. Sentence-opener diversity: repeated openers -> AI-like. Full diversity is
    #    only weak human evidence (AI varies openers too), so it floors near neutral.
    if len(sentences) >= 3:
        openers = [(_words(s) or [""])[0] for s in sentences]
        diversity = len(set(openers)) / len(openers)
        features["opener_diversity"] = _clamp(0.9 - (diversity - 0.4) * 0.9)

    # 3. Transition density: connective words/phrases per sentence -> AI-like.
    low = text.lower()
    trans = sum(1 for w in words if w in _TRANSITIONS)
    trans += sum(low.count(p) for p in _TRANSITION_PHRASES)
    density = trans / max(len(sentences), 1)
    features["transition_density"] = _clamp(density / 0.5)

    # 4. Punctuation polish: em dashes and smart quotes/ellipses -> AI-like. Their
    #    absence is not evidence of a human (AI often omits them), so it sits at a
    #    neutral baseline and only pushes upward when polish is present.
    em = text.count("—")
    smart = sum(text.count(c) for c in "“”‘’…")
    features["punctuation"] = _clamp(0.45 + (em * 1000 / n_words) + (0.35 if smart else 0.0))

    # 5. Informality: contractions and casual "i" -> human, so invert it.
    contractions = sum(1 for w in words if "'" in w)
    casual_i = len(re.findall(r"\bi\b", text))  # lowercase standalone "i"
    informal_rate = (contractions + casual_i) / n_words
    features["informality"] = _clamp(1.0 - informal_rate * 15)

    stylo_score = statistics.mean(features.values())
    return {"stylo_score": round(stylo_score, 3), "features": features}


# --------------------------------------------------------------------------- #
# Signal 3: compression / predictability (pure Python, structure-agnostic)
# --------------------------------------------------------------------------- #

# Below this many characters the zlib header/overhead dominates the ratio and the
# signal is meaningless.
_MIN_CHARS = 180

# Measured on real prose, typical English (AI or human) compresses to ~0.65. Only
# genuinely redundant, low-entropy text drops well below this. So compression is a
# one-directional cue: strong redundancy is evidence of AI, but ordinary
# compressibility is not evidence of a human. Above this ratio the signal abstains
# (returns None) and is simply left out of the ensemble rather than diluting it.
_RATIO_INFORMATIVE = 0.45


def compression_signal(text):
    """Return a redundancy-based P(AI), or abstain when uninformative.

    Returns {"compression_score": float|None, "ratio": float|None, "informative": bool}.
    Highly predictable text (repeated phrasing, low entropy) compresses smaller and
    reads AI-like. The signal only votes when it sees real redundancy; on short text
    or ordinary prose it abstains (score None) so the ensemble excludes it.
    """
    raw = text.encode("utf-8")
    if len(raw) < _MIN_CHARS:
        return {"compression_score": None, "ratio": None, "informative": False}

    ratio = len(zlib.compress(raw, 9)) / len(raw)
    if ratio >= _RATIO_INFORMATIVE:
        return {"compression_score": None, "ratio": round(ratio, 3), "informative": False}

    # Redundant enough to speak: map lower ratio -> higher P(AI).
    score = _clamp(0.5 + (_RATIO_INFORMATIVE - ratio) * 1.5)
    return {"compression_score": round(score, 3), "ratio": round(ratio, 3), "informative": True}


if __name__ == "__main__":
    # Quick standalone test: call both signals directly and inspect their output.
    samples = {
        "clearly_ai": (
            "Artificial intelligence represents a transformative paradigm shift in "
            "modern society. It is important to note that while the benefits of AI are "
            "numerous, it is equally essential to consider the ethical implications. "
            "Furthermore, stakeholders across various sectors must collaborate to "
            "ensure responsible deployment."
        ),
        "clearly_human": (
            "ok so i finally tried that new ramen place downtown and honestly? "
            "underwhelming. the broth was fine but they put WAY too much sodium in it "
            "and i was thirsty for like three hours after. my friend got the spicy "
            "version and said it was better."
        ),
    }
    for name, sample in samples.items():
        print(name, "-> groq:", groq_signal(sample))
        print(name, "-> stylo:", stylometric_signal(sample))
        print(name, "-> compression:", compression_signal(sample))
